CREATE DATABASE FIVE;

CREATE TABLE Client (
    ID SERIAL PRIMARY KEY,
    Mail VARCHAR(255) NOT NULL,
    Nom VARCHAR(255) NOT NULL,
    Prenom VARCHAR(255) NOT NULL,
    MDP VARCHAR(255) NOT NULL,
    Images VARCHAR(255)
);

CREATE TABLE Stat (
    ID SERIAL PRIMARY KEY,
    MatchJouer INTEGER,
    MatchGagner INTEGER,
    But INTEGER,
    PasseDecisive INTEGER
);

CREATE TABLE Agent (
    ID SERIAL PRIMARY KEY,
    Mail VARCHAR(255) NOT NULL,
    Nom VARCHAR(255) NOT NULL,
    Prenom VARCHAR(255) NOT NULL,
    MDP VARCHAR(255) NOT NULL,
    Roles VARCHAR(255) NOT NULL
);

CREATE TABLE Terrain (
    Nom VARCHAR(255) PRIMARY KEY,
    Capacite INTEGER,
    TypeTerrain VARCHAR(255),
    Etat VARCHAR(255),
    Images VARCHAR(255),
    Adresse VARCHAR(255)
);
